### ISSUE TITLE
Seeding data by hand?

### ISSUE THREAD

**Issue by yohannTum** [payloadcms/template-website#10]
Hello,

I am thinking about developing an open source website with payload. This template shows me a good example about seeding data but it seems that the files present in src/seed/* are made by hand.
Do I need to make them by hand if I want to open source my data? Is there a script utility already existing that I am missing for generating these kind of files based on the database?

If not, are you interesting in a pull request if I am writing this script utility?

Last question: is hiding the id collections necessary like the way you do when seeding data?

Cheers

**Comment by jacobsfletch** [comment]
Hey @yohannTum! Great question. Those files are made by hand but you could easily copy/paste the file contents from your API endpoint as a starting point, i.e. go to `/api/pages/123` and you'll receive a JSON output of the entire response. This is typically what I do as a first step in making these seed files. This way I can create documents using the Payload admin panel, then I do a little clean up by hand as needed afterwards.

This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/website. I'm going to close this issue out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).
