### ISSUE TITLE
Read me has a dead link to front end repo

### ISSUE THREAD

**Issue by ballermatic** [payloadcms/template-website#4]
THe read me states "There is a complete front-end website for this template which can be found **here**."

Where **here** links to https://github.com/payloadcms/template-website-nextjs

**Comment by jacobsfletch** [comment]
@ballermatic ahh yea that is because the nextjs template for this is still under development and so that repo was not yet public—BUT I went ahead and publicized that just now so at least it won't 404 as we continue to finish up here. Within the next couple of weeks you should start to see some real traction on that 👍
