### ISSUE TITLE
User role cannot login

### ISSUE THREAD

**Issue by steveninety** [payloadcms/template-website#7]
When creating a user with the role of user and try to log in, I get the error:

"Unauthorized, you must be logged in to make this request."
"You are not allowed to access this page."
*log out button*

The error is contradictory, because the user IS logged in. 

This is a repo clone that started with an empty, live MongoDB db. 

See screenshot:

![image](https://github.com/payloadcms/template-website/assets/93653745/a954f69d-d8ab-4ebc-b146-42a8dacf3afd)

**Comment by jacobsfletch** [comment]
Hey @steveninety! This is actually the purpose of the `admin` role—users who are allowed into the admin panel. The type `user` as you have is more like "member" of your site who can leave comments but cannot create pages, for example. They should be able to lg into your front-end, but _not_ the admin panel.

This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/website. I'm going to close this issue out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).
